package:
    name: pyg-npy
    version: 0.0.9

source:
    path: ../src
	
build:
    include_recipe: False
    number: 0
    noarch: python

requirements:
    build:
        - numpy             >=1.18.1
        - pandas            >=0.23.0
    run:
        - numpy             >=1.18.1
        - pandas            >=0.23.0
about:
    home: https://github.com/gityoav/pyg-npy
    license: GNU