package:
    name: pyg-npy
    version: 0.0.1

source:
    path: ../src
	
build:
    include_recipe: False
    number: 0
    noarch: python

requirements:
    build:
        - numpy             >=1.19.1
        - pandas            >=1.1.0
        - npy-append-array  >=0.9.13
    run:
        - numpy             >=1.19.1
        - pandas            >=1.1.0
        - npy-append-array  >=0.9.13
about:
    home: https://github.com/gityoav/pyg-npy
    license: GNU